name: CI/CD Pipeline for Flask App
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
    push:
        branches:
          - main

jobs:
    install-dependencies:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            
            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version: '3.12'
            
            - name: Install dependencies
              run: |
                pip install --upgrade pip
                pip install -r requirements.txt
    
    run-tests:
        runs-on: ubuntu-latest
        needs: install-dependencies
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            
            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version: '3.12'
            
            - name: Install dependencies
              run: |
                pip install --upgrade pip
                pip install -r requirements.txt
            
            - name: Run tests
              run: |
                python -m pytest tests/
    
    build:
        runs-on: ubuntu-latest
        needs: run-tests
        steps:
            - name: Prepare app for deployment
              run: echo "Build completed successfully."