name: CI/CD Pipeline for Flask App
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
    push:
        branches:
          - staging
    release:
        types:
            - published
jobs:
    install-dependencies:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            
            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version: '3.12'
            
            - name: Install dependencies
              run: |
                pip install --upgrade pip
                pip install -r requirements.txt
    
    run-tests:
        runs-on: ubuntu-latest
        needs: install-dependencies
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            
            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version: '3.12'
            
            - name: Install dependencies
              run: |
                pip install --upgrade pip
                pip install -r requirements.txt
            
            - name: Run tests
              run: |
                python -m pytest tests/

    deploy-staging:
        runs-on: ubuntu-latest
        needs: run-tests
        if: github.ref == 'refs/heads/staging'
        steps:
            - name: Deploy to Staging
              run: |
                echo "Deploying to staging..."

            - name: Notify via Slack or Email (optional)
              run: echo "Staging deployment finished."
              
    deploy-production:
        runs-on: ubuntu-latest
        needs: run-tests
        if: github.event_name == 'release' && github.event.action == 'published'
        steps:
            - name: Deploy to Production
              run: |
                echo "Deploying to production..."
                curl -X POST ${{ secrets.PROD_DEPLOY_URL }}

            - name: Notify Stakeholders
              run: echo "Production deployment finished."